apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: jitsi
  name: jvb
spec:
  template:
    spec:
      containers:
        - name: prometheus-exporter
          resources:
        - name: jvb
          resources:
            requests:
              cpu: "1000m"
              memory: "1000Mi"
            limits:
              memory: "1000M"
              cpu: "1000m"
